### ISSUE TITLE
use my id

### ISSUE THREAD

**Issue by SetiZ** [ingSlonik/easy-db#1]
I have a question about this easy-db.
I have a json that I need to use in a simple database. the elements look like this: 
`{
   "id": "<randomID>",
   "url": "http://example.com/"
},`
so when I insert to easy-db I get a random Id around it. Is it possible to reuse my randomID instead? I can't figure out how to do it.

**Comment by ingSlonik** [comment]
Hi SetiZ,

For this use-case is the callback in insert:
```js
const randomId = await insert("collection1", id => ({ id, url: "http://example.com/" }));
```
Is it an answer to your question?

**Comment by SetiZ** [comment]
Thank you!
At first I started doing an `insert` and then `update` but that didn't work. Just doing `update` is enough.

**Comment by ingSlonik** [comment]
You are welcome.
