### ISSUE TITLE
DB Max size

### ISSUE THREAD

**Issue by blessdarah** [ingSlonik/easy-db#2]
What is the size limit of this db storage on android? Can it be unlimited?

**Comment by ingSlonik** [comment]
Easy-DB for react-native is based on `@react-native-async-storage/async-storage` package. In the [documentation](https://react-native-async-storage.github.io/async-storage/docs/limits) for Android is written: "Total storage size is capped at 6 MB by default. You can increase this size by specifying a new size using feature flag." 

That means, that you can increase it to 10MB by adding `AsyncStorage_db_size_in_MB=10` into `android/gradle.properties`.

If you need really `unlimited` db storage. Run `easy-db-server` on server or cloud with unlimited storage. Then you can use `easy-db-client` in your phone only with change imports.

**Comment by blessdarah** [comment]
Okay, that sounds good. Thanks.
